//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dashboard1Entities : DbContext
    {
        public Dashboard1Entities()
            : base("name=Dashboard1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemGroupRel> ItemGroupRel { get; set; }
        public virtual DbSet<TabTemplate> TabTemplate { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersGroupsRel> UsersGroupsRel { get; set; }
    }
}
